Added multi-profile support (fixes #4)
caddy-dns/route53 pull request #5
Opened 2020-11-23 15:41 UTC by PhoenixPeca

Dear caddy team, this PR adds a new argument in the route53 module where people can specify which AWS profile they want to use.. If not defined, it will fall back to the default profile or the profile set in the system environment..

---

Example:

```
  tls {
      dns route53 {
        max_retries 10
        aws_profile "production-profile" # New argument for multi-profile support
      }
  }
```

For details please read this forum thread: https://caddy.community/t/automatic-https-for-route53-multi-profile-support/10512/8

2020-11-23 15:47 UTC, PhoenixPeca commented
I am not sure how you guys handle version releases of this module but i already updated some go modules as basis.. please double check before merging.. i don't want to break other people's usage.. :D

2020-11-23 17:55 UTC, mholt requested changes
Definitely lose all the changes in go.mod and go.sum. The rest LGTM.

2020-11-23 18:04 UTC, mholt requested changes
I missed a couple things

2020-11-23 18:04 UTC, mholt commented on README.md
> +    max_retries 10,
```suggestion
    max_retries 10
```

2020-11-23 18:04 UTC, mholt commented on route53.go
> +					fmt.Println(p.Provider.AwsProfile)
```suggestion
```

Remove debug line

2020-11-23 18:15 UTC, PhoenixPeca commented
Hi @mholt changes have been resolved. Thank you for taking the time to check!. :D

2020-11-24 21:46 UTC, mholt approved these changes

2020-11-25 00:14 UTC, danlsgiga commented
LGTM too! Thanks for this PR @PhoenixPeca!

2020-11-25 00:14 UTC, merged